### ISSUE TITLE
preview problem when updated to texlive 2016

### ISSUE THREAD

**Issue by subaochen** [fhackenberger/ktikz#13]
hi,

After upgrade to texlive 2016, ktikz preview windows only show part of generated picture: the top part of the picture is cutted, please refer to the attachment.
![node-distance-demo pgf- - qtikz_092](https://cloud.githubusercontent.com/assets/1390258/26087505/afe69d08-3a23-11e7-9f38-bfa1cab3dc00.png)

My test pgf file is as below:

`
\usetikzlibrary{graphs,graphdrawing}
\usegdlibrary{circular}
\begin{tikzpicture}
\graph [simple necklace layout, node distance=1cm, node sep=0pt,
nodes={draw,circle,as=.}]
{
1 -- 2 [minimum size=2cm] -- 3 --
4 -- 5 -- 6 -- 7 --[orient=up] 8
};
\draw [red,|-|] (1.center) -- ++(0:1cm);
\draw [red,|-|] (5.center) -- ++(180:1cm);
\end{tikzpicture}
`

**Comment by subaochen** [comment]
I have checked tikzpreview.cpp file，maybe there is something wrong with showPreview method ? centerPoint variable is not set?

**Comment by gprud** [comment]
Hi,

I looked at the product latex file (You can find it in the `/tmp` folder) and run `lualatex` directly from a terminal. 

Here is what I got: [temptikzcode.pdf](https://github.com/fhackenberger/ktikz/files/1441327/temptikzcode.pdf)

So, I do not think it's related to ktikz, but rather to the packages you used, maybe lualatex, or preview package.

**Comment by jfmcarreira** [comment]
Dear all,

Was it confirmed that the problem is not due to ktikz? Is it still reproducible?
