### ISSUE TITLE
app/configeditorwidget.cpp:222: suspicious expression ?

### ISSUE THREAD

**Issue by dcb314** [fhackenberger/ktikz#15]
ktikz-0.11/app/configeditorwidget.cpp:222:16: warning: '~' on an expression of type bool [-Wbool-operation]

Source code is

    if(Q_LIKELY( ~b) ) // true when the widget is initialized...

Maybe better code

    if(Q_LIKELY( !b) ) // true when the widget is initialized...

**Comment by gprud** [comment]
My mistake,
Thanks!
(fixed in branch master)
