### ISSUE TITLE
Does not build if only qt5 is installed

### ISSUE THREAD

**Issue by FrederikLauber** [fhackenberger/ktikz#19]
Hello,

while this program runs fine on a qt5 only system, building it will fail due to:
```
Info: creating stash file /tmp/makepkg/qtikz-git/src/qtikz/.qmake.stash
Project MESSAGE: *** QtikZ v0.12 ***
Project MESSAGE: Qt version: 5.10.1
Project MESSAGE: The program will be installed in
Project MESSAGE:   /usr/bin
Project MESSAGE: The resource files will be installed in
Project MESSAGE:   /usr/share/qtikz
Project MESSAGE: The documentation will be installed in
Project MESSAGE:   /usr/share/qtikz/documentation
Project MESSAGE: The desktop file will be installed in
Project MESSAGE:   /usr/share/applications
Project MESSAGE: The mimetype will be installed in
Project MESSAGE:   /usr/share/mime/packages
Project MESSAGE: The man page will be installed in
Project MESSAGE:   /usr/share/man
Project MESSAGE: 
Project MESSAGE: If you would like to change these paths,
Project MESSAGE: please adjust qtikzconfig.pri to your needs and rerun qmake.
lrelease-qt4 -silent translations/cs/qtikz_cs.ts -qm locale/qtikz_cs.qm
make: lrelease-qt4: Kommando nicht gefunden
make: *** [Makefile:1024: locale/qtikz_cs.qm] Fehler 127
```
I guess replacing lrelease-qt4 with lrelease-qt5 or lrelease would solve this.

Thanks in advance

**Comment by jfmcarreira** [comment]
LRELEASECOMMAND = lrelease-qt4 is commented in the .pri file.

Please try to uncomment it and replace "qt4" with "qt5" and see if it works. In my system I do not need to specify those commands so I am not having this problem.

I think we could update the commands to match qt5 but I think we should leave them commented.

**Comment by p91** [comment]
Hi,

as I am building within the Arch Linux AUR system, I could not easily change the code of the package BUT doing (year, horrible hack): 
```
[root@Foo bin]# ln -s lrelease-qt5 lrelease-qt4
[root@Foo bin]# ln -s qcollectiongenerator-qt5 qcollectiongenerator-qt4
```
made the program build as intended.
If you do not depend on a specific version, maybe you could just call lrelease instead of lrelease-qt4 or lrelease-qt5? Same for qcollectiongenerator.

Cheers,

**Comment by jfmcarreira** [comment]
The config does not depend, but your systems was defaulting to Qt4

**Comment by FrederikLauber** [comment]
Strange, at least in my case I had not qt4 package installed on my system

**Comment by jfmcarreira** [comment]
I agree that is strange! I just tested it out and it worked out both in Gentoo and Ubuntu 18.04.

Were you able to build after forcing Qt commands?

**Comment by FrederikLauber** [comment]
What do you mean wit forcing Qt commands? The aliasing p91 proposed? Yes, that worked.

**Comment by bjuergens** [comment]
I ran into a similar error on ubuntu 20.04: 

```
$ make
lrelease -silent ../translations/cs/qtikz_cs.ts -qm locale/qtikz_cs.qm
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory
make: *** [Makefile:775: locale/qtikz_cs.qm] Fehler 1
```

it was solved by installing 

```
sudo apt-get install qttools5-dev-tools
```

I recommend adding `qttools5-dev-tools` to the install-dependencies in INSTALL

**Comment by jfmcarreira** [comment]
Thanks for pointing it out. You built the pkg from source?

**Comment by bjuergens** [comment]
yes. I followed the instactions from [INSTALL](https://github.com/fhackenberger/ktikz/blob/master/INSTALL) for Qt-only.
