### ISSUE TITLE
Reference Screenshots from README

### ISSUE THREAD

**Issue by maxmeyer** [fhackenberger/ktikz#2]
Why not make the README a markdown-file and reference the images from there? :-)

**Comment by fhackenberger** [comment]
Done! Thanks for the hint!

**Comment by maxmeyer** [comment]
Is there any mailing list for tikz/latex you can post the new repository on?

**Comment by fhackenberger** [comment]
None in particular. Since stackexchange is so popular, I guess most support moved there...
