### ISSUE TITLE
Can it be compiled and used on my macOS ?

### ISSUE THREAD

**Issue by zhoulvwen** [fhackenberger/ktikz#24]
Can it be compiled and used on my macOS ?

**Comment by jfmcarreira** [comment]
I think if you can manage to get the right dependencies it can be built. I only build it under Linux.

Please give it a try and report your experience.

**Comment by jfmcarreira** [comment]
I do not know if you still need this but I have access to a MacOS (with Apple Silicon) and I was able to build Qtikz.

You need to install both Qt5 and Poppler-Qt5. I used homebrew for those steps. 

There was a problem with the qmake configuration which I fixed in a recent commit

**Comment by zhoulvwen** [comment]
Thank you for your reply. I still have this need.

**Comment by jfmcarreira** [comment]
It should be possible. I had to run some exports to be able to find poppler but that was something that brew warm me about. With the changes made to .pro it should be possible to build now

**Comment by zhoulvwen** [comment]
Thank you for your efforts.
