### ISSUE TITLE
Update INSTALL file

### ISSUE THREAD

**Issue by ArchangeGabriel** [fhackenberger/ktikz#26]
Build instructions still refers to qt4 package, I don’t think this is right.

**Comment by jfmcarreira** [comment]
I correct them but did not test the dependencies. I think the dependencies for Ubuntu is not a major issue here. I think the developers need to be aware of the particular needs for its own system. 

However, I updated the dependencies to match the Qt5.

**Comment by ArchangeGabriel** [comment]
I think you did not push. ;)

**Comment by jfmcarreira** [comment]
My bad!

Pushed it now
