### ISSUE TITLE
Replace text editor with KTextEditor 

### ISSUE THREAD

**Issue by jfmcarreira** [fhackenberger/ktikz#33]
I would like to have some feedback on the interest of the users to have KTextEditor replacing the current text editor widget.

This will give a similar look as Kate, Kile and other KDE text editors.

Let me know what you think.

**Comment by flying-sheep** [comment]
Yeah, definitely something I’d want. As it is now, I have to painstakingly adapt the colours for it to be usable, else it looks like this:

![image](https://user-images.githubusercontent.com/291575/74249020-cfc2df80-4ce8-11ea-9506-ee848e78ff61.png)

I don’t know how desirable the Qt version is anyway. KDE frameworks are pretty slim these days.

**Comment by jfmcarreira** [comment]
Can you build a local version? If so I would ask you to build the "develKTextEditor" branch of my ["fork"](https://github.com/jfmcarreira/ktikz/tree/develKTextEditor) and give it some testing.

If you did not find any major bug I would merge it. However, I still need to figure out how to make it as optional dependency.

**Comment by flying-sheep** [comment]
Looks nice, but you missed merging the menus and toolbars. I only see basically Kate’s menu and an editor toolbar, nothing to stop compilation, toggle shell-escape and so on.

**Comment by jfmcarreira** [comment]
You might need to perform a make install as remove the existing instalation of ktikz. You are not using the modified xml. Otherwise you would see all Tollbar and menus

**Comment by flying-sheep** [comment]
Sorry, but idk what I’m doing wrong:

```console
$ pacman -R ktikz
...
$ rm -rf build; mkdir build
$ cd build
$ cmake .. -DKTIKZ_USE_KTEXTEDITOR=1
$ make
$ ./app/ktikz
```

![image](https://user-images.githubusercontent.com/291575/74315445-bd43b700-4d77-11ea-9ed4-14510384a49b.png)

**Comment by jfmcarreira** [comment]
Sorry for the late reply.

You need to add the file `app/ktikzui_frameworks.rc` to `/usr/share/kxmlgui5/ktikz/` (or similar).
I do not recall which eviromental variable is used to set this directory.

I will try in the next weeks to merge this into master. For that I will need to add an option so both editors are available. As of this moment the auto-complete is not as good in the new editor as it is in the QT one.

**Comment by flying-sheep** [comment]
That took a while to find out. KDE probably uses something similar to:

```cpp
QStringList found = QStandardPaths::locateAll(
    QStandardPaths::GenericDataLocation,
	QStringLiteral("kxmlgui5/ktikz/ktikzui_frameworks.rc"),
);
```

QStandardPaths relies on `XDG_DATA_DIRS` on linux, soo one can prepend a directory to XDG_DATA_DIRS to make it work:

```console
$ XDG_DATA_DIRS="/my/dir:${XDG_DATA_DIRS-/usr/local/share:/usr/share}" qtpaths --paths GenericDataLocation
~/.local/share:/my/dir:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
               ^ here it is!
```

**Comment by jfmcarreira** [comment]
Yeah you are right. I asked for it in the IRC channel #kde-devel.

I managed to apply the change optionally. Just need to add a configuration option and then I will merge it to master.

I do not feel confortable to just remove the old editor. This approach allow for the user to choose.

**Comment by flying-sheep** [comment]
Ah, cool! Works great:

```console
$ mkdir -p app/kxmlgui5/ktikz
$ ln -s ../../ktikzui_frameworks.rc app/kxmlgui5/ktikz/ktikzui_frameworks.rc
$ ... cmake build dance ...
```

![grafik](https://user-images.githubusercontent.com/291575/80309194-bd2e5180-87d3-11ea-9b60-9d94475968e4.png)

For some reason I’m now seeing the built-in Oxygen icons instead of my system icons, but I think that has nothing to do with the branch.

**Comment by jfmcarreira** [comment]
I pushed a new branch `development` into this repository. It will be the new features next merged into master.

The text editor widget can be selected in the settings now. You need to restart the application in order to apply changes.

Please let me know what you think.

**Comment by flying-sheep** [comment]
Sounds good! Is KTikZ startable if compiled with KTextEditor support, but without KTextEditor installed? I think that would be optimal, because distributions could ship a binary package that has optional KTextEditor support, while users see the KTextEditor option only if they have it installed.

**Comment by jfmcarreira** [comment]
Although it would be a nice improvement I do not think the work needed to be done would be worth it.

This is my opinion: Either you want to use in KDE environment therefore there is high change you already have the KTextEditor framework installed; or you do not use KDE and you will have a better experience with the Qt-only version.

At some point KTextEditor should become the only editor with KDE enabled. However, to accomplish that I need to improve the code completion features which are not working as good as in the existing editor.

**Comment by flying-sheep** [comment]
Ah! Do you think the KTextEditor option should be the default anyway when compiled in?
