### ISSUE TITLE
Change Preview Background Color

### ISSUE THREAD

**Issue by krabo0om** [fhackenberger/ktikz#34]
Hey,

thanks for this handy tool!
But I would like to change the background color of the preview window to see how big my figure really is. Now its just white in white. Any chance such a setting will be introduced?
I use the QT version.

Thanks

**Comment by fhackenberger** [comment]
Should be quite trivial. Maybe one of the currently active contributors would be willing to add it? Maybe for a little donation, if you're willing to do that? @jfmcarreira @llimeht

**Comment by krabo0om** [comment]
Sure why not. Maybe I will look into it myself at some point. It is not an urgent matter.
