### ISSUE TITLE
How to build on Windows

### ISSUE THREAD

**Issue by upupming** [fhackenberger/ktikz#37]
Hi, any information about installing this software on Windows?

The `INSTALL-0.11.Windows` file is too old, and the steps are not practical at all!

**Comment by jfmcarreira** [comment]
I do not have any experience with windows builds. 

Did you try those instructions? If you still willing to try I could help you out.

**Comment by upupming** [comment]
@jfmcarreira Thank for your kindness, but this issue has been a long time, and now I don't use Windows anymore. I am going to close this issue.
