### ISSUE TITLE
Typo in INSTALL

### ISSUE THREAD

**Issue by david-waterworth** [fhackenberger/ktikz#39]
FYI, I think `libkf5iconthemes-devs` should be `libkf5iconthemes-dev`

https://github.com/fhackenberger/ktikz/blob/d7f983be538c8f3e6bd678a600208552326c6c4c/INSTALL#L20

**Comment by jfmcarreira** [comment]
Fixed! Thank you very much for the report. 
Maybe in the future you could issue a pull request so you can get credit for that.
