### ISSUE TITLE
any planning porting to KF5

### ISSUE THREAD

**Issue by sadhen** [fhackenberger/ktikz#4]

**Comment by fhackenberger** [comment]
Not at the moment, patches are welcome, of course!

**Comment by sadhen** [comment]
after I post the issue, I find https://github.com/jfmcarreira/ktikz. It seems to be a kf5 port.

**Comment by sadhen** [comment]
I will try to find out what I can help the next weekend.

**Comment by fhackenberger** [comment]
Duplicate of #8
