### ISSUE TITLE
Show also *.tex files in file-open dialog

### ISSUE THREAD

**Issue by VolkerChristian** [fhackenberger/ktikz#49]
It would be fine to get also all *.tex files in file open dialog.

Change

`parsedFilter += QCoreApplication::translate("FileDialog", "PGF document", "filter") + QLatin1String(" (*.pgf *.tikz)");`

to 

`parsedFilter += QCoreApplication::translate("FileDialog", "PGF document", "filter") + QLatin1String(" (*.pgf *.tikz *.tex)");`

in filedialog.cpp

**Comment by jfmcarreira** [comment]
Added. Thanks for the suggestion.
