### ISSUE TITLE
let’s merge

### ISSUE THREAD

**Issue by flying-sheep** [fhackenberger/ktikz#5]
i “forked” from the 0.10 version before you put it on github, and finished an initial KF5 port from there.

now there are two greatly diverged forks. damn.

wat do? https://github.com/flying-sheep/ktikz/tree/kde-only

**Comment by fhackenberger** [comment]
Hey! Thanks for working on ktikz, that's great! Funny thing is ktikz started as a KDE only project, hence the initial k, but was modified to include a Qt-only build due to demand on wider platform support. How's the state of the Qt-only version in your fork?

**Comment by flying-sheep** [comment]
i removed it due to KF5 being modular.

the only argument i was aware of against pulling in KDElibs was that they were friggin’ huge, which doesn’t apply anymore with KF5.

are there really platforms that people use that aren’t supported by KF5?

**Comment by jfmcarreira** [comment]
Hey guys,

I also ported your code before you created this repo. However, I created a new port to KDE Frameworks using your original Qt5 port therefore it might be usable.

You may check my fork on my github account. I would be pleased to create a pull request.

**Comment by jfmcarreira** [comment]
The current master is already based on KDE Frameworks so we can close this.

Thanks for you interest!
