### ISSUE TITLE
HELP: Unable to build kitkz for Windows

### ISSUE THREAD

**Issue by clemkofi** [fhackenberger/ktikz#50]
Hello, I have taken a look at the windows install file in the repo, but it seems a little bit outdated and some of the links are broken. After some major googling and some hours, I have been able to get it to build in QT Creator. But I keep getting two major errors.

1) there is no dll file called poppler-qt5 in the newer versions of poppler (see first pic). But rather it seems to be renamed to libpoppler-qt5-1.dll.
![image](https://user-images.githubusercontent.com/25843865/108605238-26123600-73b3-11eb-8387-e1ccb06075de.png)

2) if I change it to libpoppler-qt5-1, I am able to build an executable build it keeps giving me a procedure point could not be found error (see second pic)
![tempsnip](https://user-images.githubusercontent.com/25843865/108605298-84d7af80-73b3-11eb-9929-7d832bc84c3f.png)

Any help with this will very much appreciated... because I have been on this for a few days😅

**Comment by jfmcarreira** [comment]
I am not familiar with Windows builds. But you seem to be able to successfully build it. Seems that the problem is that the program cannot find the .dll. You need to put it in the same directory.

I am assuming you got some build version or build it within Ktikz. Either way there should be a that .dll somewhere. Can you please check.

Moreover if you can give some insights of what is outdated, I could then test it myself and update the READMEs.

**Comment by clemkofi** [comment]
Yes... so i copied the libpoppler-qt5-1 and put it into the win32/poppler folder and it gets copied to the build folder also. Thats actually when i get this error.

PS. the link to the download the gtk packages is the broken one. the new one is https://www.gtk.org/docs/installations/windows/

**Comment by jfmcarreira** [comment]
But isnt there the file libpoppler-qt-1.dll? Anywhere in the build folder?

**Comment by clemkofi** [comment]
Yes ... the libpoppler-qt5-1.dll is in the build folder and I have also copied all other associated Qt5 files into the build folder but still no luck.

This is a snapshot of the files in my build folder.
![image](https://user-images.githubusercontent.com/25843865/108716823-dfd8e600-751c-11eb-8886-97d6fb881b4a.png)

**Comment by jfmcarreira** [comment]
Ok good news.

I believe the only thing you need is to place the ktikz binary  in the same place as those DLLs. Otherwise it will not be able to find them.

Then let me know if it worked.

**Comment by clemkofi** [comment]
Which binary in particular are you referring to? .... Can you please give a hint where I should copy the binary from?

**Comment by jfmcarreira** [comment]
I already mentioned. The ktikz/qtikz binary. What I mean is the app binary/executable which is what you was trying to run when you first got that error. At least that is what I thought.

I assume that ktikz/qtikz is in a directory and the missing libraries are there but in a different one.

Just copy everything to the same place.
