### ISSUE TITLE
Unable to export PDF

### ISSUE THREAD

**Issue by AndreaDiPietro92** [fhackenberger/ktikz#51]
Selecting the KDE Frameworks Editor:
1) I'm unable to export the PDF
![image](https://user-images.githubusercontent.com/36949583/115424076-a3fd8c80-a1fe-11eb-94f4-7a12aaecc7c4.png)

2) Strange voice order in menu + disappearance of "Insert" "Process" "User Snippets"

![image](https://user-images.githubusercontent.com/36949583/115423194-e8d4f380-a1fd-11eb-8eb4-84eca47344a5.png)

With the Qt Editor is everything ok.

Kubuntu 20.10
Plasma: 5.19.5
KDE Frameworks: 5.74
Ktikz: 0.12

**Comment by jfmcarreira** [comment]
Are you able to build the latest version?

**Comment by jfmcarreira** [comment]
I was wondering if you could build version 0.13.1. I do not see that problem here. The problem is related with the KDE application is not loading the menu option from the kitkz itself and is only showing the ones related with the "KTextEditor".

**Comment by jfmcarreira** [comment]
If you build it yourself, you need to do build install so the ktikzui_frameworks.rc is acessible system-wide.

I am also not sure that version 0.12 had the KTextEditor built-in already.

**Comment by AndreaDiPietro92** [comment]
Ok. I think that is there the problem! I've build without install! 
It's my bad

Thank you

**Comment by jfmcarreira** [comment]
> Ok. I think that is there the problem! I've build without install!
> It's my bad
> 
> Thank you

Thats a common problem. There is some enviroment variable that can guide KDE to load the `ktikzui_frameworks.rc` from the build source, but I am not sure which is.

In AUR what version is built?

**Comment by AndreaDiPietro92** [comment]
> In AUR what version is built?

I'm new in ARCH, but in PARU info i get
```
Name                     : ktikz-git
Version                  : r347.64d2963-1
```

From the ` info` on the Ktikz menu i get 

```
KtikZ
Versione 0.12
```

**Comment by jfmcarreira** [comment]
Thats is an actual bug. The version is the about section is not correct. If it is from Git it should correspond to master branch and be 0.13.1

**Comment by AndreaDiPietro92** [comment]
This is what i get:


![image](https://user-images.githubusercontent.com/36949583/115431783-f7bfa400-a205-11eb-82f3-b7127b6a667d.png)

**Comment by jfmcarreira** [comment]
> This is what i get:
> 
> ![image](https://user-images.githubusercontent.com/36949583/115431783-f7bfa400-a205-11eb-82f3-b7127b6a667d.png)

That is an actually bug. I am fixing it and bump to version 0.13.2
