### ISSUE TITLE
Problem in saving file

### ISSUE THREAD

**Issue by AndreaDiPietro92** [fhackenberger/ktikz#54]
When I modify a file and save it with another name, after the save, I keep modifying the original file and not the one with the new name.

**Comment by jfmcarreira** [comment]
Thanks for reporting the issue. Are you using the latest version (with the editor similar to Kate or other Kde editors)?

I will look at that as soon as possible.

**Comment by AndreaDiPietro92** [comment]
Yes, I'm using the latest version with KDE Framework Editor

**Comment by jfmcarreira** [comment]
I believe I fixed the issue. 

Are you able to build from source and tested it?

**Comment by AndreaDiPietro92** [comment]
No, I'm not able to build it. Sorry..

**Comment by jfmcarreira** [comment]
I tagged a new version it should trigger an update in Ubuntu repositories. Then you can test it out. Closing for now
